package PJWSTK.Projekt;



import java.sql.*;

public final class DBmanager {

	private Connection connection;
	private Statement statement;
	private String url="jdbc:hsqldb:hsql://localhost/workdb";
	private ResultSet rs;
	private String createTable=
			"CREATE TABLE Person(id bigint GENERATED BY DEFAULT AS IDENTITY," +
					" name varchar(20), ID int, Pets int)";
	private String addPersonSQL="";
	private String removePersonSQL="";
	private String getAllSQL="";
	private String addPetSQL="";


	PreparedStatement addPerson;
	PreparedStatement removePerson;
	PreparedStatement getAll;
	PreparedStatement addPet;
	PreparedStatement removePet;
	PreparedStatement removeAllPets;

	private DBmanager() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			rs = connection.getMetaData().getTables(null, null, null,
			null);

			addPerson=connection.prepareStatement("");
			removePerson=connection.prepareStatement("");
			getAll=connection.prepareStatement("");
			addPet=connection.prepareStatement("");
			removePet=connection.prepareStatement("");
			removeAllPets=connection.prepareStatement("");

			} catch (SQLException e) {
			e.printStackTrace();
			}

	}

	private static DBmanager instance;

	public static DBmanager getInstance() {

		if (instance == null)
			synchronized (DBmanager.class) {
				if (instance == null)
					instance = new DBmanager();
			}
		return instance;
	}


	//metody

	void addPersonToDB(){

	}



}