package PJWSTK.Projekt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Tables {
	Connection connection ;
	Statement statement ;
	ResultSet rs;

public Tables(){
	try{
	connection = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");
	statement = connection.createStatement();	
	rs = connection.getMetaData().getTables(null, null, null, null);
	
	String createTable="CREATE TABLE Person (id bigint GENERATED BY DEFAULT AS IDENTITY," +
			" name varchar(20), ID int, Pets int,";	

	String createTable2="CREATE TABLE Pet (id bigint GENERATED BY DEFAULT AS IDENTITY," +
	" name varchar(20), ID int,";
	
	statement.executeUpdate(createTable);
	statement.executeUpdate(createTable2);
	
	
	}
	catch (SQLException e) {
	e.printStackTrace();
}
}
}

